package com.letscode.agrocinetickets.Sessionmicroservice.model.dto;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBRangeKey;
import com.letscode.agrocinetickets.Sessionmicroservice.model.Movie;
import com.letscode.agrocinetickets.Sessionmicroservice.model.Room;
import lombok.Data;

import java.time.LocalDateTime;
import java.util.UUID;

public class SessionRequest {

    @DynamoDBHashKey(attributeName = "id")
    @DynamoDBAutoGeneratedKey
    private UUID id;
    private Movie movie;
    private Room room;
    private LocalDateTime startTime;
    private boolean[][] seats;
}

