package com.letscode.agrocinetickets.Sessionmicroservice.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBRangeKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.Data;

@DynamoDBTable(tableName = "session")
@Data
public class Movie {

    @DynamoDBRangeKey(attributeName = "id")
    @DynamoDBAutoGeneratedKey
    private String id;
    @DynamoDBHashKey
    private String type;
    private String title;
    private Long year;
    private Long runtime;
    private String director;
    private String poster;
    private boolean subtitle;
}
